### ISSUE TITLE
Roofer v1.0 overview

### ISSUE THREAD

**Issue by Ylannl** [3DBAG/roofer#1]
- [x] Transfer necessary function for building reconstruction from geoflow code (mostly gfp-building-reconstruction) and untangle from geoflow architecture. No big refactoring yet.
- [x] Build up and test building reconstruction pipeline (ie. what used to be reconstruct flowchart)
- [x] Make executable programs (crop and reconstruct) for running reconstruction pipeline by end user feature complete. Should be usable as drop in replacement for current geoflow reconstruct flowchart.
- [x] Develop API 
  - [x]  #7 Simple C++ api that wraps the basic building reconstruction pipeline
  - [x] #13
- [x] Refactor code. Focus on common datatypes, minimise code duplication etc.
  - [x] Update ArrangementOptimiser to latest CGAL api
  - [x] remove proj dependency
  - [x] Consistent logging 
    - [x] compile flag to turn off logging and remove dependency
    - [x] make logging backend easily replaceable (#14)
  - [x] Revise cmake build system, dependency management (vcpkg?) and project folder structure (#18)
  - [x] test and set minimal versions for cmake dependencies + only require dependencies if targets are requested that need them
  - [x] put everything in roofer namespaces
  - [x] License in header of each file
  - [x] consistent coding style (see how to set up clang-tidy and clang-format https://github.com/3DGI/roofer-dev/tree/develop/experiments/clang-tools) (#18)
  - [x] update val3dity to current version (possibly need to refactor val3dity itself)
  - [x] integrate ~jemalloc~ mimalloc
  - [x] fix "Warning 1: Layer 'geom' has been declared with non-Z geometry type Polygon, but it does contain geometries with Z. Setting the Z=2 hint into gpkg_geometry_columns" in VectorWriter
- [x] Improvements to handle very large input data without needing a separate pre-tiling step
  - [x] #8
  - [x] #9
  - [x] Test with real large data on gilfoyle
- [x] Improve error handling roofer app
  - [x] don't crash if a building reconstruction fails but throw exception and continue reconstruction with next buildings/tiles.
  - [x] output failed building with attribute reconstruction_status='failed' 
- [x] #10
- [x] Polish apps
  - [x] Check if output paths exits and are writable prior to do expensive computations
  - [x] Update cli parameters/usage
  - [x] integrate crop/reconstruct apps into roofer
- [x] #34 
- [x] Automated testing
  - [x] Integration tests of the apps (#18)
  - [x] Test that the app installation is done correctly (#18)
  - [x] make default `ctest` tests succeed without install
